//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alquiler_cliente
    {
        public int alq_id { get; set; }
        public int cli_id { get; set; }
        public System.DateTime ac_fec_asig { get; set; }
        public string ac_est { get; set; }
    
        public virtual alquileres alquileres { get; set; }
        public virtual clientes clientes { get; set; }
    }
}
