//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alquileres
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public alquileres()
        {
            this.alquiler_cliente = new HashSet<alquiler_cliente>();
            this.alquiler_proyecto = new HashSet<alquiler_proyecto>();
        }
    
        public int alq_id { get; set; }
        public Nullable<int> equ_id { get; set; }
        public Nullable<System.DateTime> alq_fec_ini { get; set; }
        public Nullable<System.DateTime> alq_fec_fin_est { get; set; }
        public Nullable<System.DateTime> alq_fec_fin_re { get; set; }
        public string alq_est { get; set; }
    
        public virtual equipos equipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alquiler_cliente> alquiler_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alquiler_proyecto> alquiler_proyecto { get; set; }
    }
}
