//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente_proyecto
    {
        public int cli_id { get; set; }
        public int proy_id { get; set; }
        public Nullable<System.DateTime> cp_fecha { get; set; }
        public string cp_rol { get; set; }
        public string cp_est { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual proyectos proyectos { get; set; }
    }
}
