//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public clientes()
        {
            this.cliente_proyecto = new HashSet<cliente_proyecto>();
            this.ventas = new HashSet<ventas>();
            this.alquiler_cliente = new HashSet<alquiler_cliente>();
            this.servicios_cliente = new HashSet<servicios_cliente>();
        }
    
        public int cli_id { get; set; }
        public string cli_ced { get; set; }
        public string cli_nom { get; set; }
        public string cli_ape { get; set; }
        public string cli_tel { get; set; }
        public Nullable<int> ciu_id { get; set; }
        public string cli_dir { get; set; }
        public string cli_email { get; set; }
        public string cli_est { get; set; }
        public Nullable<System.DateTime> cli_fecha { get; set; }
    
        public virtual ciudad ciudad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cliente_proyecto> cliente_proyecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ventas> ventas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alquiler_cliente> alquiler_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<servicios_cliente> servicios_cliente { get; set; }
    }
}
