//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class compras
    {
        public int comp_id { get; set; }
        public Nullable<int> prove_id { get; set; }
        public string comp_tip_doc { get; set; }
        public string comp_num_doc { get; set; }
        public Nullable<decimal> comp_total { get; set; }
        public string comp_est { get; set; }
        public Nullable<int> usu_id { get; set; }
    
        public virtual proveedores proveedores { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
