//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleados
    {
        public int emp_id { get; set; }
        public string emp_ced { get; set; }
        public string emp_nom { get; set; }
        public string emp_ape { get; set; }
        public Nullable<int> cargo_id { get; set; }
        public Nullable<decimal> emp_salario { get; set; }
        public Nullable<int> ciu_id { get; set; }
        public Nullable<System.DateTime> emp_fec_contrat { get; set; }
        public string emp_tel { get; set; }
        public string emp_est { get; set; }
    
        public virtual cargos cargos { get; set; }
        public virtual ciudad ciudad { get; set; }
    }
}
