//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public equipos()
        {
            this.alquileres = new HashSet<alquileres>();
        }
    
        public int equ_id { get; set; }
        public string equ_nom { get; set; }
        public string equ_desc { get; set; }
        public Nullable<decimal> equ_prec_com { get; set; }
        public Nullable<decimal> equ_prec_ven { get; set; }
        public int equ_stock { get; set; }
        public Nullable<System.DateTime> equ_fec { get; set; }
        public string equ_est { get; set; }
        public Nullable<int> mar_id { get; set; }
        public string equ_code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alquileres> alquileres { get; set; }
        public virtual marcas marcas { get; set; }
    }
}
