//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proyectos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public proyectos()
        {
            this.proyecto_tarea = new HashSet<proyecto_tarea>();
            this.alquiler_proyecto = new HashSet<alquiler_proyecto>();
            this.cliente_proyecto = new HashSet<cliente_proyecto>();
            this.proyecto_servicio = new HashSet<proyecto_servicio>();
        }
    
        public int proy_id { get; set; }
        public string proy_nom { get; set; }
        public string proy_desc { get; set; }
        public Nullable<System.DateTime> proy_fecha_inicio { get; set; }
        public Nullable<System.DateTime> proy_fecha_fin_est { get; set; }
        public Nullable<System.DateTime> proy_fecha_fin_real { get; set; }
        public Nullable<decimal> proy_presupuesto { get; set; }
        public string proy_est { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<proyecto_tarea> proyecto_tarea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alquiler_proyecto> alquiler_proyecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cliente_proyecto> cliente_proyecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<proyecto_servicio> proyecto_servicio { get; set; }
    }
}
