//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proyecto_tarea
    {
        public int proy_id { get; set; }
        public int tar_id { get; set; }
        public System.DateTime pt_fec_ini { get; set; }
        public Nullable<System.DateTime> pt_fec_fin { get; set; }
        public Nullable<System.DateTime> pt_fec_fin_real { get; set; }
        public string pt_est { get; set; }
    
        public virtual proyectos proyectos { get; set; }
        public virtual tareas tareas { get; set; }
    }
}
