//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proyecto_servicio
    {
        public Nullable<int> proy_id { get; set; }
        public Nullable<int> serv_id { get; set; }
        public System.DateTime ps_fec_asig { get; set; }
        public string ps_est { get; set; }
    
        public virtual proyectos proyectos { get; set; }
        public virtual servicios servicios { get; set; }
    }
}
