//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaWebMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConstructoraBDEntities : DbContext
    {
        public ConstructoraBDEntities()
            : base("name=ConstructoraBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alquileres> alquileres { get; set; }
        public virtual DbSet<cargos> cargos { get; set; }
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<ciudad> ciudad { get; set; }
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<compras> compras { get; set; }
        public virtual DbSet<empleados> empleados { get; set; }
        public virtual DbSet<equipos> equipos { get; set; }
        public virtual DbSet<marcas> marcas { get; set; }
        public virtual DbSet<materiales> materiales { get; set; }
        public virtual DbSet<pagos> pagos { get; set; }
        public virtual DbSet<proveedores> proveedores { get; set; }
        public virtual DbSet<provincia> provincia { get; set; }
        public virtual DbSet<proyecto_tarea> proyecto_tarea { get; set; }
        public virtual DbSet<proyectos> proyectos { get; set; }
        public virtual DbSet<servicios> servicios { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tareas> tareas { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<ventas> ventas { get; set; }
        public virtual DbSet<alquiler_cliente> alquiler_cliente { get; set; }
        public virtual DbSet<alquiler_proyecto> alquiler_proyecto { get; set; }
        public virtual DbSet<cliente_proyecto> cliente_proyecto { get; set; }
        public virtual DbSet<proyecto_servicio> proyecto_servicio { get; set; }
    }
}
