//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ventas
    {
        public int ven_id { get; set; }
        public Nullable<int> cli_id { get; set; }
        public Nullable<int> pag_id { get; set; }
        public string ven_tip_doc { get; set; }
        public string ven_num_doc { get; set; }
        public Nullable<decimal> ven_mont_pag { get; set; }
        public Nullable<decimal> ven_mont_camb { get; set; }
        public Nullable<decimal> ven_mont_tot { get; set; }
        public Nullable<System.DateTime> ven_fec { get; set; }
        public string ven_est { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual pagos pagos { get; set; }
    }
}
